<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="Current">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>14.0</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>nullable</WarningsAsErrors>
		<AnalysisMode>All</AnalysisMode>
		<AnalysisLevel>latest</AnalysisLevel>
		<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
		<ImplicitUsings>true</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
		<UseArtifactsOutput>true</UseArtifactsOutput>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>None</DebugType>
		<DebugSymbols>False</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Nullable.Extended.Analyzer" Version="1.15.6169">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Roslynator.Analyzers" Version="4.12.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SonarAnalyzer.CSharp" Version="10.3.0.106239">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
